language: cpp
matrix:
  allow_failures:
    - compiler: clang
  fast_finish: true
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data
            - g++-4.9
            - libconfig++-dev
            - valgrind
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data
            - g++-5
            - libconfig++-dev
            - valgrind
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data
            - clang-3.6
            - libconfig++-dev
            - valgrind
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data
            - clang-3.7
            - libconfig++-dev
            - valgrind
      env: COMPILER=clang++-3.7

branches:
  only:
    - master

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  - valgrind ./goiovalues
