language: cpp

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

matrix:
  # allow_failures:
  #   - compiler: clang
  fast_finish: true
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data
            - g++-4.9
            - libconfig++-dev
            - valgrind
      env:
        - CXX_COMPILER=g++-4.9 C_COMPILER=gcc-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data
            - g++-5
            - libconfig++-dev
            - valgrind
      env:
        - CXX_COMPILER=g++-5 C_COMPILER=gcc-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data
            - clang-3.6
            - libconfig++-dev
            - valgrind
      env:
        - CXX_COMPILER=clang++-3.6 C_COMPILER=clang-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data
            - clang-3.7
            - libconfig++-dev
            - valgrind
      env:
        - CXX_COMPILER=clang++-3.7 C_COMPILER=clang-3.7

branches:
  only:
    - master

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && make
  - valgrind --leak-check=full --error-exitcode=1 ./goiovalues
